# Generated by Django 5.1.1 on 2024-09-26 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('measurement', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('article', models.CharField(max_length=50)),
                ('warranty', models.PositiveSmallIntegerField()),
                ('condition', models.CharField(choices=[('Новое', 'Новое'), ('БУ', 'Бывшее в Употреблении'), ('ТР', 'Требует Ремонт')], max_length=50)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.countries')),
            ],
        ),
    ]
