# Generated by Django 5.1.1 on 2024-09-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
